### ISSUE TITLE
Bug: PopUpWindow 클릭 시 오작동

### ISSUE THREAD

**Issue by sjsjsj1246** [Hipspot/hipspot-web#16]
**버그를 설명해주세요**
클러스터링 리스트가 열려있을 때 팝업윈도우를 열면 정상 작동함
그러나 클러스터링 리스트를 닫고 팝업 윈도우를 열면 인포윈도우의 width, height가 비정상적으로 커져 overflow됨

가로가 커지는 문제는 클러스터링 리스트가 오른쪽으로 가면서 부모의 width가 화면보다 커져 생기는 문제일 것 같음
infowindow의 width를 100%가 아닌 100vw로 변경하여 해결 할 수 있으나 여전히 오작동은 있음

**재현방법**
버그를 재현하려면...
1. main에서 pnpm start
2. 클러스터링 리스트 닫기
3. 팝업 스크린 바 작동
4. 인포 윈도우가 영역을 벗어나 좌우 스크롤 가능해짐, 축소 동작도 가능해짐

**맞는 동작**
인포윈도우가 커지지 않음

**스크린샷**

정상
![정상](https://user-images.githubusercontent.com/24623403/213880061-441599b8-7b7b-4dde-b603-6fb8b0fe9805.gif)

비정상
![비정상](https://user-images.githubusercontent.com/24623403/213880065-0214c508-890b-497a-9e1d-4489b0bb1cc0.gif)

**추가적인 상황**

다음과 같이 any 타입을 없애는 리펙토링 작업을 하다가 발견함
```ts
작업 전
      const slideEvent: any = new Event('forSlide');
      slideEvent.clientY = e.touches[0].clientY;
      document.getElementById('slide')?.dispatchEvent(slideEvent);
---
작업 후
      const slideEvent: Event = Object.assign(new Event('forSlide'), { clientY: e.touches[0].clientY });
      document.getElementById('slide')?.dispatchEvent(slideEvent);

이 사항은 버그 픽스 후에도 마찬가지로 적용 바람
```
문제 원인 파악 필요하여 제보

**Comment by Sangjun-man** [comment]
내용을 좀 추가하자면 저 slide 커스텀 이벤트는 인포윈도우 top 위치에 따라서 연속적으로 이미지 리스트 크기 키워줄때 사용했었습니다~
