### ISSUE TITLE
Bug: geoJson의 카페 아이디와 실제 아이디가 다름

### ISSUE THREAD

**Issue by hyorish03** [Hipspot/hipspot-web#23]
**버그를 설명해주세요**
geoJson에서 가져온 카페 아이디가 실제 카페 아이디가 다릅니다.

**재현방법**

**맞는 동작**

**스크린샷**
geoJson에서 가져온 카페 데이터 ( 아이디 11번이 카페 노티드)
![image](https://user-images.githubusercontent.com/108210492/214247981-99f6903b-218c-48b2-9d37-38672d2639d9.png)

실제 카페 데이터 (아이디 10번이 카페 노티드)
![image](https://user-images.githubusercontent.com/108210492/214248065-a20d937e-2154-4c23-ac95-e25400d79b5c.png)

아이디가 1씩 차이 나네요

**추가적인 상황**
문제를 해결하는데 도움되는 당시의 상황을 적어주세요.

**Comment by yeoularu** [comment]
<img width="1134" alt="스크린샷 2023-01-25 시간: 21 47 48" src="https://user-images.githubusercontent.com/69510981/214567437-938d8d9e-dffa-449d-bd7a-a2d81693fc90.png">

/map 요청에서 몇몇 아이디 비어있고, 아이디 2씩 다르기도 합니다

**Comment by Sangjun-man** [comment]
음 여기는 임시 데이터라 ui 랜더링이 잘 되는지만 확인하면 될것같아요~ 추후 실제 api에도 문제가 있으면 그때 수정해도 좋을것같습니다~
